name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.detect.outputs.matrix }}
    steps:
      - id: detect
        run: |
          echo '::set-output name=matrix::{"action":["templates/typescript"]}'

  run:
    runs-on: ubuntu-latest
    needs:
      - detect
    strategy:
      matrix: ${{ fromJSON(needs.detect.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.action }}
    steps:
      - uses: actions/checkout@v3
      - id: node-version
        run: echo "::set-output name=version::$(cat .nvmrc)"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package
      - run: yarn lint
      - run: yarn test

  wait-test:
    needs:
      - detect
      - run
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - run: exit 1
